import { test, type TestContext } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { AccountingDatabase } from 'print-accounting-database';
import { AccountingService, CollectionBusyError } from '../apps/server/src/service.ts';
import { apiFixture } from './api-fixtures.ts';
import type { InkResponse, JobsResponse, LedgerJob, MediaTypesResponse, PapersResponse, TotalsResponse } from 'print-accounting-contracts';
import { batch, MEDIA, sample } from './fixtures.ts';
const options = { host: '127.0.0.1', cacheDirectory: '/unused' };
function fixture(t: TestContext) {
  const dir = mkdtempSync(join(tmpdir(), 'printtally-api-')), db = new AccountingDatabase(join(dir, 'db.sqlite3'));
  t.after(() => { db.close(); rmSync(dir, { recursive: true }); });
  return db;
}
test('collection failure records safe category, releases lock and does not persist raw errors', async t => {
  const db = fixture(t);
  const service = new AccountingService(db, async () => { throw new Error('synthetic-secret-that-must-not-persist'); });
  await assert.rejects(service.collect(options, async () => 'synthetic password'));
  assert.equal(service.busy, false);
  const rows = db.all('SELECT * FROM import_runs');
  assert.equal(rows[0].error_code, 'collection_failed'); assert.equal(rows[0].status, 'failed');
  assert.ok(!JSON.stringify(rows).includes('synthetic-secret'));
});
test('simultaneous collections share one service lock', async t => {
  const db = fixture(t);
  let release!: () => void;
  const barrier = new Promise<void>(resolve => { release = resolve; });
  const service = new AccountingService(db, async () => { await barrier; return sample(); });
  const password = async () => 'synthetic password';
  const first = service.collect(options, password);
  await assert.rejects(service.collect(options, password), CollectionBusyError);
  release(); assert.equal((await first).result.new_jobs, 1);
  assert.equal(db.summary().import_runs, 1);
});
test('API validates annotations, keeps hidden jobs accessible and returns safe collection failures', async t => {
  const f = await apiFixture(t, { collector: async () => { throw new Error('secret printer data'); }, inspectRoot: async () => { throw new Error('offline'); } });
  f.db.importSnapshot(sample());
  const request = (path: string, method = 'GET', body?: unknown) => f.request('/api/v1' + path, { method, body });
  assert.equal((await request('/jobs?limit=1001')).status, 400);
  assert.equal((await request('/jobs/999')).status, 404);
  const patch = (body: unknown) => request('/jobs/1/annotation', 'PATCH', body);
  assert.equal((await patch({ media_config_id: 99 })).status, 400);
  assert.equal((await patch({ physical_sheet_count: 1 })).status, 400);
  assert.equal((await patch({ custom_paper_name: 'Sample sheet', hidden: 1 })).status, 200);
  assert.equal((await request('/jobs')).json<{ jobs: unknown[] }>().jobs.length, 0);
  assert.equal((await request('/jobs?includeHidden=true')).json<{ jobs: unknown[] }>().jobs.length, 1);
  const detail = (await request('/jobs/1')).json<{ job: { display_paper_name: string; ink: unknown[] } }>();
  assert.equal(detail.job.display_paper_name, 'Sample sheet'); assert.equal(detail.job.ink.length, 2);
  assert.equal((await request('/collect', 'POST', {})).status, 404);
  const printer = await f.addPrinter('10.23.45.67', 'synthetic password');
  const collection = await request(`/known-printers/${printer.id}/collect`, 'POST', {});
  assert.equal(collection.status, 502); assert.deepEqual(collection.json(), { error: 'printer_unreachable' });
  assert.ok(!collection.text.includes('secret printer data'));
  assert.equal(f.db.get('SELECT status FROM import_runs ORDER BY id DESC')!.status, 'failed');
});
test('API manages papers, stock, purchases, ink and write-offs and returns costed, searchable jobs', async t => {
  const f = await apiFixture(t), db = f.db;
  db.importSnapshot(batch([{ day: '2026-02-01' }, { day: '2026-02-02', imp: 2 }]));
  const call = async (method: string, path: string, body?: unknown) => {
    const reply = await f.request('/api/v1' + path, { method, body });
    return { status: reply.status, body: reply.json<Record<string, never>>() };
  };
  const created = async (path: string, body: unknown) => { const reply = await call('POST', path, body); assert.equal(reply.status, 201, JSON.stringify(reply.body)); return reply.body.id as number; };
  const paper = await created('/papers', { name: 'Museum Etching', media_types: [MEDIA] });
  const a4 = await created('/paper-stocks', { paper_id: paper, name: 'A4', format: 'sheet', width_um: 210000, height_um: 297000 });
  await created('/paper-purchases', { paper_stock_id: a4, purchased_on: '2026-01-01', packs: 2, sheets_per_pack: 25, price_micros: 50_000_000 });
  const cyan = await created('/ink-cartridges', { name: 'PFI-1000 C', channel: 'C', capacity_nl: 80_000_000 });
  await created('/ink-purchases', { ink_product_id: cyan, purchased_on: '2026-01-01', cartridges: 1, price_micros: 40_000_000 });
  const off = await created('/write-offs', { paper_stock_id: a4, written_off_on: '2026-02-03', quantity: 3, reason: 'Creased' });
  assert.equal((await call('POST', '/paper-purchases', { paper_stock_id: a4, purchased_on: '2026-01-01', length_um: 5, price_micros: 1 })).status, 400);
  assert.equal((await call('POST', '/papers', { name: 'Museum Etching' })).status, 409);
  assert.equal((await call('POST', '/papers', { name: 'Extra', unexpected: true })).status, 400);
  assert.equal((await call('DELETE', '/paper-stocks/' + a4)).status, 409);
  assert.equal((await call('PATCH', '/papers/999', { name: 'Missing' })).status, 404);
  assert.equal((await call('POST', '/unknown-things', {})).status, 404);
  assert.deepEqual((await call('PATCH', '/write-offs/' + off, { quantity: 4 })).body, { updated: true });
  const detail = (await call('GET', '/jobs/2')).body.job as unknown as LedgerJob;
  assert.deepEqual([detail.paper.stock_id, detail.paper.cost_micros, detail.total_micros], [a4, 2_000_000, 2_000_000 + 62_500]);
  assert.equal((await call('PATCH', '/jobs/2/annotation', { notes: 'Edition 1/10' })).status, 200);
  const search = (await call('GET', '/jobs?q=EDITION')).body as unknown as JobsResponse;
  assert.deepEqual([search.total, search.jobs[0].job_id, search.settings.currency], [1, 2, 'GBP']);
  assert.deepEqual((await call('PATCH', '/settings', { costing_method: 'max' })).body, { costing_method: 'max', currency: 'GBP' });
  assert.equal((await call('PATCH', '/settings', { currency: 'gbp' })).status, 400);
  const totals = (await call('GET', '/totals')).body as unknown as TotalsResponse;
  assert.deepEqual([totals.overall.jobs, totals.overall.paper_micros, totals.overall.waste_micros], [2, 3_000_000, 4_000_000]);
  const papers = (await call('GET', '/papers')).body as unknown as PapersResponse;
  assert.equal(papers.papers[0].stock[0].remaining, 50 - 3 - 4);
  assert.equal(((await call('GET', '/ink')).body as unknown as InkResponse).cartridges[0].remaining, 80_000_000 - 2 * 125_000);
  assert.equal(((await call('GET', '/media-types')).body as unknown as MediaTypesResponse).media_types[0].papers[0].id, paper);
  assert.deepEqual((await call('DELETE', '/write-offs/' + off)).body, { deleted: true });
});
