/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as CenteredRouteImport } from './routes/_centered'
import { Route as AppCollectRouteImport } from './routes/_app/collect'
import { Route as AppInkRouteImport } from './routes/_app/ink'
import { Route as AppJobsRouteImport } from './routes/_app/jobs'
import { Route as AppPapersRouteImport } from './routes/_app/papers'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as CenteredConnectRouteImport } from './routes/_centered/connect'
import { Route as CenteredSetupRouteImport } from './routes/_centered/setup'
import { Route as AppInkIndexRouteImport } from './routes/_app/ink.index'
import { Route as AppInkChannelRouteImport } from './routes/_app/ink.$channel'
import { Route as AppInkNewRouteImport } from './routes/_app/ink.new'
import { Route as AppJobsIndexRouteImport } from './routes/_app/jobs.index'
import { Route as AppJobsJobIdRouteImport } from './routes/_app/jobs.$jobId'
import { Route as AppPapersIndexRouteImport } from './routes/_app/papers.index'
import { Route as AppPapersPaperIdRouteImport } from './routes/_app/papers.$paperId'
import { Route as AppPapersNewRouteImport } from './routes/_app/papers.new'
import { Route as AppPapersMediaIndexRouteImport } from './routes/_app/papers.media.index'
import { Route as AppPapersMediaMediaRouteImport } from './routes/_app/papers.media.$media'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const CenteredRoute = CenteredRouteImport.update({
  id: '/_centered',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCollectRoute = AppCollectRouteImport.update({
  id: '/collect',
  path: '/collect',
  getParentRoute: () => AppRoute,
} as any)
const AppInkRoute = AppInkRouteImport.update({
  id: '/ink',
  path: '/ink',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppPapersRoute = AppPapersRouteImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const CenteredConnectRoute = CenteredConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => CenteredRoute,
} as any)
const CenteredSetupRoute = CenteredSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => CenteredRoute,
} as any)
const AppInkIndexRoute = AppInkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInkRoute,
} as any)
const AppInkChannelRoute = AppInkChannelRouteImport.update({
  id: '/$channel',
  path: '/$channel',
  getParentRoute: () => AppInkRoute,
} as any)
const AppInkNewRoute = AppInkNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppInkRoute,
} as any)
const AppJobsIndexRoute = AppJobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppJobsRoute,
} as any)
const AppJobsJobIdRoute = AppJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => AppJobsRoute,
} as any)
const AppPapersIndexRoute = AppPapersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPapersRoute,
} as any)
const AppPapersPaperIdRoute = AppPapersPaperIdRouteImport.update({
  id: '/$paperId',
  path: '/$paperId',
  getParentRoute: () => AppPapersRoute,
} as any)
const AppPapersNewRoute = AppPapersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppPapersRoute,
} as any)
const AppPapersMediaIndexRoute = AppPapersMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => AppPapersRoute,
} as any)
const AppPapersMediaMediaRoute = AppPapersMediaMediaRouteImport.update({
  id: '/media/$media',
  path: '/media/$media',
  getParentRoute: () => AppPapersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collect': typeof AppCollectRoute
  '/ink': typeof AppInkRouteWithChildren
  '/jobs': typeof AppJobsRouteWithChildren
  '/papers': typeof AppPapersRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/connect': typeof CenteredConnectRoute
  '/setup': typeof CenteredSetupRoute
  '/ink/$channel': typeof AppInkChannelRoute
  '/ink/new': typeof AppInkNewRoute
  '/jobs/$jobId': typeof AppJobsJobIdRoute
  '/papers/$paperId': typeof AppPapersPaperIdRoute
  '/papers/new': typeof AppPapersNewRoute
  '/ink/': typeof AppInkIndexRoute
  '/jobs/': typeof AppJobsIndexRoute
  '/papers/': typeof AppPapersIndexRoute
  '/papers/media/$media': typeof AppPapersMediaMediaRoute
  '/papers/media/': typeof AppPapersMediaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collect': typeof AppCollectRoute
  '/settings': typeof AppSettingsRoute
  '/connect': typeof CenteredConnectRoute
  '/setup': typeof CenteredSetupRoute
  '/ink/$channel': typeof AppInkChannelRoute
  '/ink/new': typeof AppInkNewRoute
  '/jobs/$jobId': typeof AppJobsJobIdRoute
  '/papers/$paperId': typeof AppPapersPaperIdRoute
  '/papers/new': typeof AppPapersNewRoute
  '/ink': typeof AppInkIndexRoute
  '/jobs': typeof AppJobsIndexRoute
  '/papers': typeof AppPapersIndexRoute
  '/papers/media/$media': typeof AppPapersMediaMediaRoute
  '/papers/media': typeof AppPapersMediaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_centered': typeof CenteredRouteWithChildren
  '/_app/collect': typeof AppCollectRoute
  '/_app/ink': typeof AppInkRouteWithChildren
  '/_app/jobs': typeof AppJobsRouteWithChildren
  '/_app/papers': typeof AppPapersRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_centered/connect': typeof CenteredConnectRoute
  '/_centered/setup': typeof CenteredSetupRoute
  '/_app/ink/$channel': typeof AppInkChannelRoute
  '/_app/ink/new': typeof AppInkNewRoute
  '/_app/jobs/$jobId': typeof AppJobsJobIdRoute
  '/_app/papers/$paperId': typeof AppPapersPaperIdRoute
  '/_app/papers/new': typeof AppPapersNewRoute
  '/_app/ink/': typeof AppInkIndexRoute
  '/_app/jobs/': typeof AppJobsIndexRoute
  '/_app/papers/': typeof AppPapersIndexRoute
  '/_app/papers/media/$media': typeof AppPapersMediaMediaRoute
  '/_app/papers/media/': typeof AppPapersMediaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collect'
    | '/ink'
    | '/jobs'
    | '/papers'
    | '/settings'
    | '/connect'
    | '/setup'
    | '/ink/$channel'
    | '/ink/new'
    | '/jobs/$jobId'
    | '/papers/$paperId'
    | '/papers/new'
    | '/ink/'
    | '/jobs/'
    | '/papers/'
    | '/papers/media/$media'
    | '/papers/media/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collect'
    | '/settings'
    | '/connect'
    | '/setup'
    | '/ink/$channel'
    | '/ink/new'
    | '/jobs/$jobId'
    | '/papers/$paperId'
    | '/papers/new'
    | '/ink'
    | '/jobs'
    | '/papers'
    | '/papers/media/$media'
    | '/papers/media'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_centered'
    | '/_app/collect'
    | '/_app/ink'
    | '/_app/jobs'
    | '/_app/papers'
    | '/_app/settings'
    | '/_centered/connect'
    | '/_centered/setup'
    | '/_app/ink/$channel'
    | '/_app/ink/new'
    | '/_app/jobs/$jobId'
    | '/_app/papers/$paperId'
    | '/_app/papers/new'
    | '/_app/ink/'
    | '/_app/jobs/'
    | '/_app/papers/'
    | '/_app/papers/media/$media'
    | '/_app/papers/media/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CenteredRoute: typeof CenteredRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_centered': {
      id: '/_centered'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CenteredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/collect': {
      id: '/_app/collect'
      path: '/collect'
      fullPath: '/collect'
      preLoaderRoute: typeof AppCollectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ink': {
      id: '/_app/ink'
      path: '/ink'
      fullPath: '/ink'
      preLoaderRoute: typeof AppInkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/papers': {
      id: '/_app/papers'
      path: '/papers'
      fullPath: '/papers'
      preLoaderRoute: typeof AppPapersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_centered/connect': {
      id: '/_centered/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof CenteredConnectRouteImport
      parentRoute: typeof CenteredRoute
    }
    '/_centered/setup': {
      id: '/_centered/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof CenteredSetupRouteImport
      parentRoute: typeof CenteredRoute
    }
    '/_app/ink/': {
      id: '/_app/ink/'
      path: '/'
      fullPath: '/ink/'
      preLoaderRoute: typeof AppInkIndexRouteImport
      parentRoute: typeof AppInkRoute
    }
    '/_app/ink/$channel': {
      id: '/_app/ink/$channel'
      path: '/$channel'
      fullPath: '/ink/$channel'
      preLoaderRoute: typeof AppInkChannelRouteImport
      parentRoute: typeof AppInkRoute
    }
    '/_app/ink/new': {
      id: '/_app/ink/new'
      path: '/new'
      fullPath: '/ink/new'
      preLoaderRoute: typeof AppInkNewRouteImport
      parentRoute: typeof AppInkRoute
    }
    '/_app/jobs/': {
      id: '/_app/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AppJobsIndexRouteImport
      parentRoute: typeof AppJobsRoute
    }
    '/_app/jobs/$jobId': {
      id: '/_app/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AppJobsJobIdRouteImport
      parentRoute: typeof AppJobsRoute
    }
    '/_app/papers/': {
      id: '/_app/papers/'
      path: '/'
      fullPath: '/papers/'
      preLoaderRoute: typeof AppPapersIndexRouteImport
      parentRoute: typeof AppPapersRoute
    }
    '/_app/papers/$paperId': {
      id: '/_app/papers/$paperId'
      path: '/$paperId'
      fullPath: '/papers/$paperId'
      preLoaderRoute: typeof AppPapersPaperIdRouteImport
      parentRoute: typeof AppPapersRoute
    }
    '/_app/papers/new': {
      id: '/_app/papers/new'
      path: '/new'
      fullPath: '/papers/new'
      preLoaderRoute: typeof AppPapersNewRouteImport
      parentRoute: typeof AppPapersRoute
    }
    '/_app/papers/media/': {
      id: '/_app/papers/media/'
      path: '/media'
      fullPath: '/papers/media/'
      preLoaderRoute: typeof AppPapersMediaIndexRouteImport
      parentRoute: typeof AppPapersRoute
    }
    '/_app/papers/media/$media': {
      id: '/_app/papers/media/$media'
      path: '/media/$media'
      fullPath: '/papers/media/$media'
      preLoaderRoute: typeof AppPapersMediaMediaRouteImport
      parentRoute: typeof AppPapersRoute
    }
  }
}

interface AppInkRouteChildren {
  AppInkChannelRoute: typeof AppInkChannelRoute
  AppInkNewRoute: typeof AppInkNewRoute
  AppInkIndexRoute: typeof AppInkIndexRoute
}

const AppInkRouteChildren: AppInkRouteChildren = {
  AppInkChannelRoute: AppInkChannelRoute,
  AppInkNewRoute: AppInkNewRoute,
  AppInkIndexRoute: AppInkIndexRoute,
}

const AppInkRouteWithChildren =
  AppInkRoute._addFileChildren(AppInkRouteChildren)

interface AppJobsRouteChildren {
  AppJobsJobIdRoute: typeof AppJobsJobIdRoute
  AppJobsIndexRoute: typeof AppJobsIndexRoute
}

const AppJobsRouteChildren: AppJobsRouteChildren = {
  AppJobsJobIdRoute: AppJobsJobIdRoute,
  AppJobsIndexRoute: AppJobsIndexRoute,
}

const AppJobsRouteWithChildren =
  AppJobsRoute._addFileChildren(AppJobsRouteChildren)

interface AppPapersRouteChildren {
  AppPapersPaperIdRoute: typeof AppPapersPaperIdRoute
  AppPapersNewRoute: typeof AppPapersNewRoute
  AppPapersIndexRoute: typeof AppPapersIndexRoute
  AppPapersMediaMediaRoute: typeof AppPapersMediaMediaRoute
  AppPapersMediaIndexRoute: typeof AppPapersMediaIndexRoute
}

const AppPapersRouteChildren: AppPapersRouteChildren = {
  AppPapersPaperIdRoute: AppPapersPaperIdRoute,
  AppPapersNewRoute: AppPapersNewRoute,
  AppPapersIndexRoute: AppPapersIndexRoute,
  AppPapersMediaMediaRoute: AppPapersMediaMediaRoute,
  AppPapersMediaIndexRoute: AppPapersMediaIndexRoute,
}

const AppPapersRouteWithChildren = AppPapersRoute._addFileChildren(
  AppPapersRouteChildren,
)

interface AppRouteChildren {
  AppCollectRoute: typeof AppCollectRoute
  AppInkRoute: typeof AppInkRouteWithChildren
  AppJobsRoute: typeof AppJobsRouteWithChildren
  AppPapersRoute: typeof AppPapersRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCollectRoute: AppCollectRoute,
  AppInkRoute: AppInkRouteWithChildren,
  AppJobsRoute: AppJobsRouteWithChildren,
  AppPapersRoute: AppPapersRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CenteredRouteChildren {
  CenteredConnectRoute: typeof CenteredConnectRoute
  CenteredSetupRoute: typeof CenteredSetupRoute
}

const CenteredRouteChildren: CenteredRouteChildren = {
  CenteredConnectRoute: CenteredConnectRoute,
  CenteredSetupRoute: CenteredSetupRoute,
}

const CenteredRouteWithChildren = CenteredRoute._addFileChildren(
  CenteredRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CenteredRoute: CenteredRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
